### ISSUE TITLE
关于基座模型

### ISSUE THREAD

**Issue by Kouuh** [SUSTech-IDEA/SUS-Chat#2]
想问下项目是在原始的lllama2上只进行了sft 嘛？还是有对他做中文的增加预训练

**Comment by fecet** [comment]
我们的模型并非基于Llama2预训练模型，且Llama2预训练模型并没有34B的权重。我们的模型基于零一万物发布的Yi-34B-Base模型，其huggingface的地址为https://huggingface.co/01-ai/Yi-34B 。

**Comment by xycjscs** [comment]
请在readme显眼处明确说明所使用的基座模型。
