### ISSUE TITLE
提供的模板貌似不适用system message

### ISSUE THREAD

**Issue by luo-li-ba-suo** [SUSTech-IDEA/SUS-Chat#3]
`def chat_template(messages):
    history = ""
    for message in messages:
        match message:
            case {"role": "user", "content": message}:
                history += f"### Human: {message}\n\n### Assistant: "
            case {"role": "assistant", "content": message}:
                history += message
    return history`
这是SUS模型主页提供的模板，貌似不包含system message的情况，是直接视作user message吗？

**Comment by fecet** [comment]
是的，暂时没有对system message特殊对待
