### ISSUE TITLE
加载模型报错

### ISSUE THREAD

**Issue by uloveqian2021** [SUSTech-IDEA/SUS-Chat#4]
从modelscope上下载的模型，加载过程中报错
ValueError: Trying to set a tensor of shape torch.Size([1024, 7168]) in "weight" (which has shape torch.Size([7168, 7168])), this look incorrect.

**Comment by azusa-li** [comment]
请问朋友这个问题你是怎么解决的呢，我也遇到一样的问题了。卡了很久。
